### ISSUE TITLE
Make splitting ratio of mother daughter variable

### ISSUE THREAD

**Issue by StudDavid** [StudDavid/biofilm_growth_modeling#18]

**Comment by jonmueller11** [comment]
i think this could work:
the following code multiplys a mother/doughter ratio to the length (mother/doughter distribution from the paper)
daughter_bac_length = self.length * np.random.normal(0.5, 0.5 * 0.07)
the following code gives the mothers lenght
self.length = self.length - daughter_bac_length

furthermore i think the scipy pdf- function should be replaced with the scipy cdf function

**Comment by StudDavid** [comment]
Yes, this seems like a good way to do this

**Comment by StudDavid** [comment]
This feature was included in v. 1.0.2
